ARG NODE_VERSION=20.10.0

FROM node:${NODE_VERSION} as base

ARG PORT=3000

ENV NODE_ENV=production

WORKDIR /src

FROM base as build
COPY --link . .
RUN npm install --production=false
RUN npx prisma generate

# Run
# FROM base

# COPY --from=build /src/node_modules /src/node_modules

CMD [ "npm", "run", "dev" ]